### ISSUE TITLE
I can not obtain the HotpotQA_classified.jsonl

### ISSUE THREAD

**Issue by Alternate-D** [Yueeeeeeee/Self-Supervised-QA#2]
sorry to bother you, Mr. Yue. But a problem occurred when I run qc4qa_trec.py to obtain HotpotQA_classified.jsonl which is explained in detail below:

when I run this command CUDA_VISIBLE_DEVICES=0 python src/qc4qa_trec.py, an error occurred which is:

Traceback (most recent call last):
  File "src/qc4qa_trec.py", line 153, in <module>
    encoder = make_embed_fn("https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/3")
  File "src/qc4qa_trec.py", line 63, in make_embed_fn
    embed = hub.Module(module)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/module.py", line 157, in __init__
    self._spec = as_module_spec(spec)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/module.py", line 30, in as_module_spec
    return load_module_spec(spec)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/module.py", line 65, in load_module_spec
    return registry.loader(path)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/native_module.py", line 139, in __call__
    module_def_proto = self._get_module_def_proto(path)
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow_hub/native_module.py", line 130, in _get_module_def_proto
    module_def_proto.ParseFromString(f.read())
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/ln01/anaconda3/envs/self-supervised-QA/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 81, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/tfhub_modules/00be90ccc24323f05839f37c308417d7e0e977ed/tfhub_module.pb; No such file or directory

I considered it's perhaps a version-related error, so I accessed the website  "https://tfhub.dev/google/universal-sentence-encoder-large/3" , then I find that the version 3 of the universal-sentence-encoder-large model has been deprecated, and now only the version 5 of that model is available. Could you please give me some advice?

**Comment by Yueeeeeeee** [comment]
In this case, please directly use version 5 instead
